### PR TITLE
Migrate to latest version of webview_flutter

### PR DESCRIPTION
**Pull request by MAlazhariy**
Migrate code to the latest version of `webview_flutter` (4.1.0).

### CODE REVIEW

**Comment by MAlazhariy** [comment]
This update prevents conflicts with other packages that use a newer version of `webview_flutter` when `Flutter pub get` or even if the package is used directly in the project.
Therefore, it is recommended to migrate the package to be up-to-date.

**Comment by Alexandros-Konstantakos-Wesser** [comment]
Does this work? It would be nice to have this merged! :)

**Comment by MAlazhariy** [comment]
@Alexandros-Konstantakos-Wesser 
**Yes it works.**
You need to install it like that in the `pubspec.yaml` file:
```
vimeo_player_flutter:
    git: https://github.com/MAlazhariy/vimeo_player.git
```
till they merge it into the package.

**Comment by pbattistella** [comment]
@MAlazhariy and @Alexandros-Konstantakos-Wesser , please can aprove this mr? this is an important update.

**Comment by MAlazhariy** [comment]
@prahack ?

**Review by prahack — APPROVED** [review]

**Comment by pbattistella** [comment]
Thank you guys!

**Pull request merged**
